services:
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres
    networks:
      - best-coffee-network
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    image: temporalio/auto-setup
    networks:
      - best-coffee-network
    ports:
      - 7233:7233
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui
    networks:
      - best-coffee-network
    ports:
      - 8080:8080
  orchestrator-service:
    container_name: orchestrator-service
    image: python:3
    depends_on:
      - temporal
    volumes:
      - ./orchestrator-service:/app
      - ./requirements.txt:/requirements.txt
      - ./init.sh:/init.sh
    entrypoint: sh -c "chmod -R 755 /app && chmod -R 755 /init.sh && sh /init.sh"
    networks:
      - best-coffee-network
  payment-service:
    container_name: payment-service
    image: python:3
    depends_on:
      - temporal
    volumes:
      - ./payment-service:/app
      - ./requirements.txt:/requirements.txt
      - ./init.sh:/init.sh
    entrypoint: sh -c "chmod -R 755 /app && chmod -R 755 /init.sh && sh /init.sh"
    networks:
      - best-coffee-network

    
networks:
  best-coffee-network:
    driver: bridge
    name: best-coffee-network